<!DOCTYPE bdcorreo[
<!ELEMENT bdcorreo (email)+>
<!ELEMENT email (destinatario,asunto,cuerpo)>
<!ELEMENT destinatario (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT cuerpo (#PCDATA)>
]>
<bdcorreo>
    <email>
        <destinatario></destinatario>
        <asunto></asunto>
        <cuerpo></cuerpo>
    </email>
    <email>
        <destinatario></destinatario>
        <asunto></asunto>
        <cuerpo></cuerpo>
    </email>
</bdcorreo>